name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: [ '8.1', '8.2', '8.3']
        sf_version: [ '5.4', '6.4', '7.1' ]
        exclude:
          - php: 8.1
            sf_version: 7.1

    steps:
      - uses: actions/checkout@v2
      - name: Validate composer-5.4.json
        run: composer validate --strict

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Override Symfony version
        run: composer run ci-symfony-install-version ${{ matrix.sf_version }}

      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php }}
          memory_limit: 1024M
          version: 9
          bootstrap: vendor/autoload.php
